name: Terraform Deploy

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    #  Use the 'Production' environment to access secrets.
    environment: Production
    
    env:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_WORKSPACE: ${{ vars.TF_CLOUD_WORKSPACE }}
      TF_WORKING_DIRECTORY: ./infra-terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN_APP_TERRAFORM_IO }}

      - name: Upload configuration and trigger TFC run
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        with:
          workspace: ${{ env.TF_CLOUD_WORKSPACE }}
          directory: ${{ env.TF_WORKING_DIRECTORY }}
          token: ${{ secrets.TF_CLOUD_TOKEN_APP_TERRAFORM_IO }}
