name: Terraform Deploy

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    environment: Production
    
    env:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }} # 🚨 UPDATED: Using GitHub Actions Environment Variable
      TF_CLOUD_WORKSPACE: ${{ vars.TF_CLOUD_WORKSPACE }}      # 🚨 UPDATED: Using GitHub Actions Environment Variable

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Terraform Cloud Login
        run: |
          # The TF_API_TOKEN is passed directly to the `terraform login` command.
          echo "${{ secrets.TF_CLOUD_TOKEN_APP_TERRAFORM_IO }}" | terraform login - -app-password
        
      - name: Terraform Init
        working-directory: ./infra-terraform
        run: terraform init
        
      # The following steps are no longer needed for a VCS-driven workflow.
      # Terraform Cloud handles the plan and apply steps automatically after a push.
      # You can, however, use dedicated actions to control the run if needed.
      # For a basic push, Terraform Cloud will automatically trigger a plan and apply.
      
      # - name: Terraform Plan
      # - name: Terraform Apply
      
      # Optional: To manually trigger a run via the API, you would use a different action.
      # This is often used for non-VCS-driven workflows.
      
      # - name: Upload configuration to TFC
      #   uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
      #   id: upload
      #   with:
      #     workspace: ${{ env.TF_CLOUD_WORKSPACE }}
      #     directory: ./infra-terraform
      #     speculative: true # Set to true for PRs, false for master branch pushes
      #   env:
      #     TFE_TOKEN: ${{ secrets.TF_CLOUD_TOKEN_APP_TERRAFORM_IO }}

      # - name: Create a new TFC run
      #   uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
      #   with:
      #     workspace: ${{ env.TF_CLOUD_WORKSPACE }}
      #     configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
      #     is_destroy: false # Set to true to destroy infrastructure
      #   env:
      #     TFE_TOKEN: ${{ secrets.TF_CLOUD_TOKEN_APP_TERRAFORM_IO }}
